version: '3.8'

services:
  mysql-db:
    image: mysql:8
    container_name: apes-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: apes
    ports:
      - "3306:3306"